# This is a template TOML input file
N_missions = 1 # Number of missions to be modeled


[Options] #
fueltype      = "LH2" # Choices are LH2 or Jet-A
fuelinwing    = false # Is fuel stored in wings?
fuelinwingcen = false # Is fuel stored in wing center box?

HTsize = 2 # Options are 1: set Sh via Vh
           #             2: set Sh via igCLhCGfwd at max-forward CG during landing
VTsize = 1 #

movewingbox = 2 # 0: fix wing position 
                # 1: move wing to get CLh=CLhspec in cruise 
                # 2: move wing to get min static margin = SMmin
engloc = 2 # 1: Engines on wing
           # 2: Engines on fuselage
closefuse = 0 # 0: Fuselage tapers to a point
              # 1: Fuselage tapers to an edge
coreBLI = 0 # 0: Core in clean flow

wingplanform = 1 # 1: Wing cantilever with engine

strut_braced_wing = false


#engweight = 0 # currently not implemented in ZITAopt, could allow for different engine weight models in the future

[Mission]
pax = 220            # Number of passengers
range = "3000.0 nmi" # Design Range

W_per_pax = "215.0 lbf" # Specify weight per passenger - includes luggage [lbm or lbf or kg or N] judging you if you use imperial units but wtvs

[Fuselage]

[Propulsion]
